### ISSUE TITLE
Working in docker

### ISSUE THREAD

**Issue by Vctrsnts** [khenriks/mp3fs#72]
Hi.

I use the version on docker with this docker-compose.yml on debian bulleyes:
```
  mp3fs:
    image: khenriks/mp3fs
    container_name: mp3fs
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - "my_music_home":/music/input
      - /tmp/mp3:/music/output
    command: -b 160
```

And I put my music files in "**my_music_home**". I have anything?

Because if I use the comands that you put on docker section :
```
$ MUSICDIR="my_music_home" MP3DIR=/tmp/mp3 MP3FS_FLAGS="-b 160" \
  docker-compose up mp3fs
```
Not have anything.

Where is my error?

Thanks a lot
